### PR TITLE
Add find and replace function

### PR DESCRIPTION
**Pull request by ehanson8**
#### What does this PR do?
Creates a find and replace function and adds corresponding test (which may or may not be too elaborate)

#### Includes new or updated dependencies?
NO

### CODE REVIEW

**Review by gravesm — COMMENTED** [review]
This is good, but I think we may want to consider making `find_and_replace` take a record object rather than doing the searching and fetching itself. There are a couple reasons for this. First, it will make this much easier to test. Second, this function's job is to modify text in the notes of a record. It shouldn't need to know anything about the client or how to get a record.

This will likely mean a few more changes elsewhere. Rather than this function updating a record, it should probably just return the record and something else will be responsible for updating it.

**Comment by ehanson8** [comment]
I probably should have been clearer in my description of this, I'm intending this to be a sort of über-wrapper function for the full find and replace workflow which utilizes a number of existing functions (search, replace_str, save_record etc.) This replaces a lot of the code I had set up in cli.py for this workflow and which I will be using frequently. Is there a better way I should organize or name this to achieve this goal?

**Comment by ehanson8** [comment]
Made some edits. I'm still torn on removing the `save_record` function from this function because I like the ability to do a test run using the `makes_edits` parameter. Any suggestions for how to accomplish without duplicating most of this code in another function?

**Comment by ehanson8** [comment]
I'm juggling around the `csv_row` variable and the `cli.py` edits allow a test run that writes to the CSV and avoid filling it with entries where there were no changes. I'm definitely open to other ideas if you see a more efficient way

**Pull request closed without merging**
