### PR TITLE
create agents workflow

### PR DESCRIPTION
**Pull request by ehanson8**
#### What does this PR do?
Adds functionality for creating personal and corporate agents in ArchivesSpace and outputting a new agent report that connects the newly created agent URIs to the source metadata. Includes corresponding unit and cli tests for the new code.

#### Includes new or updated dependencies?
NO

### CODE REVIEW

**Comment by gravesm** [comment]
I have some suggestions for this, but I want to better understand the data first.
1. Are there fields in the CSV with values that don't end up in the agent dictionary? Like is there a `foo` field in the CSV that you just don't add to the dictionary?
2. When you have, e.g.:
```python
if title != '':
        name['title'] = title
```
does this mean that you *do* want the agent dictionary to have a `title` key with `None` if that's what the CSV reader returns?

**Comment by ehanson8** [comment]
1. Yes, the match point in the CSV doesn't go into the agent record. It's used for new record report that will be used to crosswalk the original string to the new agent URI in a later workflow
2. No, if there is no value for a field in the metadata CSV, that field shouldn't appear in the agent record
Does that all make sense?

**Comment by gravesm** [comment]
OK, you should probably also account for `None` values in addition to empty strings in your `create_agent` functions. What I would suggest in those functions, instead of checking if the argument is not empty, is to just set the value to whatever was passed to the function and then filter empty values out of the dictionary. So something like:
```python
import operator

f = operator.itemgetter(1)

# Then in your create_agent functions:
names = dict(filter(f, names.items()))
```

That won't descend into nested dictionaries, so you'll need to do that for the names and dates dictionaries individually.

**Comment by ehanson8** [comment]
Excellent, I'll loop around to that and update the PR, thanks!

**Comment by ehanson8** [comment]
Updated the PR based on @gravesm 's comments

**Comment by ehanson8** [comment]
A 2nd minor update of moving the date creation code into a separate function because I will be reusing it in another workflow. Added a corresponding test as well

**Review by gravesm — APPROVED** [review]
Not a blocking change, but I'll note that while not incorrect
```python
if some_key in some_dict.keys()
```
can be rewritten as
```python
if some_key in some_dict
```
because the membership test operation for dictionaries automatically looks at keys.

**Pull request merged**
